project:
  name: quickstart-amazon-marketing-cloud
  owner: quickstart-eng@amazon.com
  package_lambda: false
  s3_regional_buckets: true
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: 'quickstart-amazon-marketing-cloud/'
  regions:
    #- af-south-1
    #- ap-east-1
    #- ap-south-1
   # - ap-northeast-3
    #- ap-northeast-2
    #- ap-southeast-1
    #- ap-southeast-2
    #- ap-northeast-1
    #- ca-central-1
    # - cn-north-1
    # - cn-northwest-1
    #- eu-central-1
    #- eu-west-1
    #- eu-west-2
    #- eu-south-1
    #- eu-west-3
    #- eu-north-1
    #- me-south-1
   # - sa-east-1
    - us-east-1
    #- us-east-2
    #- us-west-1
    - us-west-2
tests:
  default:
    parameters:
      EmailAddress: override
      Username: robot
    template: templates/quickstart-amc-enrypoint.template.yaml
    regions:
    - us-east-1
    - us-west-2
