AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "DynamoDB Resources for the team"

Parameters:
  pEnvironment:
    Type: String
  pKMSInfraKeyId:
    Type: String
  pTeamName:
    Type: String

Resources:

  ### Update with Customer CONFIG table
  rDynamoCustomerConfig:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: customer_hash_key
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: customer_hash_key
          AttributeType: S
        - AttributeName: amc_hash_key
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: amc-index
          KeySchema:
            - AttributeName: amc_hash_key
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
         PointInTimeRecoveryEnabled: true
      TableName: !Sub "sdlf-${pTeamName}-customer-config-${pEnvironment}"
      SSESpecification:
        SSEEnabled: True
        SSEType: KMS
        KMSMasterKeyId: !Ref pKMSInfraKeyId
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  rDynamoCustomerConfigTableSsm:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/SDLF/Dynamo/${pTeamName}/CustomerConfig"
      Type: "String"
      Value: !Sub "sdlf-${pTeamName}-customer-config-${pEnvironment}"
      Description: "Name of the DynamoDB used to store customer configuration"
