AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Contains all the resources necessary for the wofkflow management microservice"

Parameters:
  pTeamName:
    Type: String
    AllowedPattern: '[a-z0-9]{2,10}'
  pMicroserviceName:
    Type: String
    AllowedPattern: '[a-z0-9]{2,12}'
  pPipelineName:
    Type: String
    AllowedPattern: '[a-z0-9]{2,10}'
    
Resources:

  rSNSSQSKey:
    Type: AWS::KMS::Key
    Properties: 
      Description: String
      Enabled: true
      KeyPolicy: 
        Version: '2012-10-17'
        Id: key-consolepolicy-3
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
          Action: kms:*
          Resource: '*'
        - Sid: Enable Codebuild to Modify
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:role/sdlf-${pMicroserviceName}-cicd-codebuild'
          Action: kms:*
          Resource: '*'
        - Sid: Enable SQS and sns Access
          Effect: Allow
          Principal:
            Service:
            - sns.amazonaws.com
            - sqs.amazonaws.com
          Action:
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey*
          - kms:CreateGrant
          - kms:DescribeKey
          Resource: '*'
      Tags: 
        -
          Key: 'tagging-policy'
          Value: !Join ['-', [!Ref pMicroserviceName, !Ref pTeamName, !Ref pPipelineName, !Ref AWS::StackName,  "common"]]
  
  rSNSSQSKeyAlias:
    Type: AWS::KMS::Alias
    Properties: 
      AliasName: !Sub "alias/sdlf-${pMicroserviceName}-kms-sqs-sns-key"
      TargetKeyId: !Ref rSNSSQSKey

Outputs:
  oSNSSQSKeyAlias:
    Value: !Ref rSNSSQSKeyAlias
  oSNSSQSKey:
    Value: !Ref rSNSSQSKey
    