AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Contains all the resources necessary for the wofkflow management microservice"

Parameters:
  pTeamName:
    Type: String
    AllowedPattern: '[a-z0-9]{2,10}'
  pMicroserviceName:
    Type: String
    AllowedPattern: '[a-z0-9]{2,12}'
  pPipelineName:
    Type: String
    AllowedPattern: '[a-z0-9]{2,10}'
  pKMSKeyId:
    Type: String

Resources:

######### DynamoDB Tables #######
  rDynamoDBCustomerConfig:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
      # ProvisionedThroughput:
      #   ReadCapacityUnits: 5
      #   WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref pKMSKeyId
      TableName: !Join ['-', [!Ref pMicroserviceName, !Ref pTeamName, !Ref pPipelineName,  "CustomerConfig"]]

  rDynamoDBAMCWorkflows:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: workflowId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: workflowId
          KeyType: RANGE
      # ProvisionedThroughput:
      #   ReadCapacityUnits: 5
      #   WriteCapacityUnits: 5
      StreamSpecification: 
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref pKMSKeyId
      TableName: !Join ['-', [!Ref pMicroserviceName, !Ref pTeamName, !Ref pPipelineName,  "AMCWorkflows"]]

  rDynamoDBAMCWorkflowLibrary:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: workflowId
          AttributeType: S
        - AttributeName: version
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: workflowId
          KeyType: HASH
        - AttributeName: version
          KeyType: RANGE
      # ProvisionedThroughput:
      #   ReadCapacityUnits: 5
      #   WriteCapacityUnits: 5
      StreamSpecification: 
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref pKMSKeyId
      TableName: !Join ['-', [!Ref pMicroserviceName, !Ref pTeamName, !Ref pPipelineName,  "AMCWorkflowLibrary"]]

  rDynamoDBAMCWorkflowSchedules:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: Name
          AttributeType: S
        - AttributeName: ScheduleExpression
          AttributeType: S
        - AttributeName: State
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: custom-schdl-index
          KeySchema:
            - AttributeName: ScheduleExpression
              KeyType: HASH
            - AttributeName: State
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: Name
          KeyType: RANGE
      # ProvisionedThroughput:
      #   ReadCapacityUnits: 5
      #   WriteCapacityUnits: 5
      StreamSpecification: 
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref pKMSKeyId
      TableName: !Join ['-', [!Ref pMicroserviceName, !Ref pTeamName, !Ref pPipelineName,  "AMCSchedules"]]

  rDynamoDBAMCExecutionStatus:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: workflowExecutionId
          AttributeType: S
        - AttributeName: executionStatus
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: workflowExecutionId
          KeyType: RANGE
      # ProvisionedThroughput:
      #   ReadCapacityUnits: 5
      #   WriteCapacityUnits: 5
      StreamSpecification: 
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref pKMSKeyId
      GlobalSecondaryIndexes :
        -
          IndexName: executionStatus-workflowId-index
          KeySchema:
            -
              AttributeName: "customerId"
              KeyType: "HASH"
            -
              AttributeName: "executionStatus"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "workflowExecutionId"
              - "workflowId"
              - "createTime"
              - "invalidationOffsetSecs"
              - "lastUpdatedTime"
              - "outputS3URI"
              - "timeWindowStart"
              - "timeWindowStartOriginal"
              - "timeWindowEnd"
              - "timeWindowEndOriginal"
              - "parameterValues"
              - "timeWindowType"
              - "statusReason"
            ProjectionType: "INCLUDE"
      #     ProvisionedThroughput:
      #       ReadCapacityUnits: "5"
      #       WriteCapacityUnits: "5"
      # PointInTimeRecoverySpecification:
      #   PointInTimeRecoveryEnabled: true
      TableName: !Join ['-', [!Ref pMicroserviceName, !Ref pTeamName, !Ref pPipelineName,  "AMCExecutionStatus"]]

  rCustomerConfigTableSSM:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/SDLF/Dynamo/${pMicroserviceName}/CustomerConfig"
      Type: "String"
      Value: !Ref rDynamoDBCustomerConfig
      Description: !Sub "Name of the CustomerConfig ${pMicroserviceName} DDB TABLE"

Outputs:
  oDynamoDBAMCExecutionStatus:
    Value: !Ref rDynamoDBAMCExecutionStatus
  oDynamoDBAMCExecutionStatusStreamArn:
    Value: !GetAtt rDynamoDBAMCExecutionStatus.StreamArn
  
  oDynamoDBAMCWorkflowSchedules:
    Value: !Ref rDynamoDBAMCWorkflowSchedules
  oDynamoDBAMCWorkflowSchedulesStreamArn:
    Value: !GetAtt rDynamoDBAMCWorkflowSchedules.StreamArn
  
  oDynamoDBAMCWorkflows:
    Value: !Ref rDynamoDBAMCWorkflows
  oDynamoDBAMCWorkflowsStreamArn:
    Value: !GetAtt rDynamoDBAMCWorkflows.StreamArn

  oDynamoDBCustomerConfig:
    Value: !Ref rDynamoDBCustomerConfig
  oDynamoDBCustomerConfigStreamArn:
    Value: !GetAtt rDynamoDBCustomerConfig.StreamArn
  
  oDynamoDBAMCWorkflowLibrary: 
    Value: !Ref rDynamoDBAMCWorkflowLibrary
  oDynamoDBAMCWorkflowLibraryStreamArn:
    Value: !GetAtt rDynamoDBAMCWorkflowLibrary.StreamArn