AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "DynamoDB resources to manage a team"
Parameters:
  pMicroserviceName:
    Type: String
  pTeamName:
    Type: String
  pPipelineName:
    Type: String
  pEnvironment:
    Type: String
  pKMSKeyId:
    Type: String
Resources:
  ####### DynamoDB Tables #######
  # rDynamoDBTenantConfig:
  #   Type: 'AWS::DynamoDB::Table'
  #   Properties:
  #     AttributeDefinitions:
  #       - AttributeName: tenantId
  #         AttributeType: S
  #       - AttributeName: tenantName
  #         AttributeType: S
  #     BillingMode: PROVISIONED
  #     KeySchema:
  #       - AttributeName: tenantId
  #         KeyType: HASH
  #       - AttributeName: tenantName
  #         KeyType: RANGE
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 5
  #       WriteCapacityUnits: 5
  #     StreamSpecification:
  #       StreamViewType: NEW_AND_OLD_IMAGES
  #     PointInTimeRecoverySpecification:
  #       PointInTimeRecoveryEnabled: true
  #     TableName: !Join ['-', [!Ref pMicroserviceName, !Ref pTeamName, "TenantConfig", !Ref pEnvironment]]
  #     Tags:
  #       - Key: 'tagging-policy'
  #         Value: !Join ['-', [!Ref pMicroserviceName, !Ref pTeamName, !Ref pEnvironment]]

  rDynamoDBCustomerConfig:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: customerName
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: customerName
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
         PointInTimeRecoveryEnabled: true
      TableName: !Join ['-', [!Ref pMicroserviceName, !Ref pTeamName, "CustomerConfig", !Ref pEnvironment]]
      SSESpecification:
        SSEEnabled: True
        SSEType: KMS
        KMSMasterKeyId: !Ref pKMSKeyId
      Tags:
        - Key: 'tagging-policy'
          Value: !Join ['-', [!Ref pMicroserviceName, !Ref pTeamName, !Ref pEnvironment]]
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
      
  
  #### SSM Parameter######
  # rSSMTenantDynamoDBTable:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Name:
  #       Fn::Sub: /SDLF/Dynamo/${pTeamName}/${pMicroserviceName}/TenantConfig
  #     Type: String
  #     Value: !Join ['-', [!Ref pMicroserviceName, !Ref pTeamName, "TenantConfig", !Ref pEnvironment]]
  #     Description: Name of the DynamoDB used to store tenant configuration



Outputs:
  # oTenantTableName:
  #   Description: "Tenant Table name"
  #   Value: !Select [1, !Split ['/', !GetAtt rDynamoDBTenantConfig.Arn]]
  # oDynamoDBTenantStream:
  #   Description: "Arn of the Tenant DynamoDB Stream"
  #   Value: !GetAtt rDynamoDBTenantConfig.StreamArn
  # oTenantTableNameSSM:
  #   Description: "Tenant Table name"
  #   Value: !Ref rSSMTenantDynamoDBTable
  oCustomerConfigTableName:
    Description: "Customer Config Table name"
    Value: !Select [1, !Split ['/', !GetAtt rDynamoDBCustomerConfig.Arn]]
  # oDynamoDBTenantTable:
  #   Description: "Arn of the Customer Config DynamoDB Table"
  #   Value: !GetAtt rDynamoDBTenantConfig.Arn
  oDynamoDBCustomerConfigStream:
    Description: "Arn of the Customer Config DynamoDB Table"
    Value: !GetAtt rDynamoDBCustomerConfig.StreamArn