AWSTemplateFormatVersion: "2010-09-09"
Description: "SNS resources to manage a team"
Parameters:
  pMicroserviceName:
    Type: String
  pTeamName:
    Type: String
  pPipelineName:
    Type: String
  pEnvironment:
    Type: String
  pSNSIntegrationKeyAlias:
    Type: String
  # pSNSIntegrationKey:
  #   Type: String

Resources:

  
  # rTenantConfigSNSTopic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     TopicName: !Sub "${pMicroserviceName}-${pTeamName}-TenantConfig-SNSTopic-${pEnvironment}.fifo"
  #     FifoTopic: true
  #     KmsMasterKeyId: !Ref pSNSIntegrationKeyAlias
  #     ContentBasedDeduplication: true
  #     Tags:
  #       -
  #         Key: 'tagging-policy'
  #         Value: !Sub "${pMicroserviceName}-${pTeamName}-${pEnvironment}"

  rCustomerConfigSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${pMicroserviceName}-${pTeamName}-CustomerConfig-SNSTopic-${pEnvironment}.fifo"
      FifoTopic: true
      KmsMasterKeyId: !Ref pSNSIntegrationKeyAlias
      ContentBasedDeduplication: true
      Tags:
        -
          Key: 'tagging-policy'
          Value: !Sub "${pMicroserviceName}-${pTeamName}-${pEnvironment}"

Outputs:

  oCustomerConfigSNSTopic:
    Description: "AMC Customer Config SNS topic"
    Value: !Ref rCustomerConfigSNSTopic

  # oTenantConfigSNSTopic:
  #   Description: "AMC Customer Config SNS topic"
  #   Value: !Ref rTenantConfigSNSTopic